services:
  valheim_server:
    image: tsxcloud/valheim-arm:latest
    restart: unless-stopped
    stop_grace_period: 40s

    cpus: "3.5"
    mem_limit: 10g
    mem_reservation: 4g
    pids_limit: 512
    
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    
    environment:
      SERVER_NAME: ${SERVER_NAME}
      SERVER_WORLD: ${SERVER_WORLD}
      SERVER_PASSWORD: ${SERVER_PASSWORD}
      SERVER_VISIBILITY: ${SERVER_VISIBILITY:-0}
      SERVER_SAVE_INTERVAL: ${SERVER_SAVE_INTERVAL:-1800}
      SERVER_BACKUPS: ${SERVER_BACKUPS:-4}
      SERVER_BACKUP_SHORT: ${SERVER_BACKUP_SHORT:-7200}
      SERVER_BACKUP_LONG: ${SERVER_BACKUP_LONG:-43200}
      ENABLE_PLUGINS: ${ENABLE_PLUGINS:-false}
      ENABLE_CROSSPLAY: ${ENABLE_CROSSPLAY:-false}
    
    healthcheck:
      test:
        - CMD-SHELL
        - 'pgrep -f "[v]alheim_server.exe" >/dev/null || exit 1'
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 180s
    
    volumes:
      - valheim-server:/root/valheim-server
      - valheim-data:/root/.config/unity3d/IronGate/Valheim
    #This is required for ntsync to work inside Docker.
    #If ntsync support is not enabled in your Linux kernel, comment out this section, otherwise Docker Compose won't start.
#    devices:
#      - /dev/ntsync:/dev/ntsync
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  valheim-server:
  valheim-data:
